appName: AATT_APP_NAME-frontend # This value was modified by the initial-setup python script

deployment:
  image:
    repository: AATT_DOCKERHUB_USERNAME/AATT_APP_NAME-frontend # This value was modified by the initial-setup python script

configmap:
  images: |-
    var images = [
        "https://i.imgur.com/2Z8qEvC.png", // Terraform destroy seagull
        "https://i.imgur.com/weNsDia.jpg", // Explaining my K8S architecture
        "https://i.imgur.com/dgB9Olt.jpg", // Thanos infinity devops stones
        "https://i.imgur.com/2Xntz2P.jpg", // Gitops Winnie the Pooh
        "https://i.imgur.com/pIGcI2d.jpg", // Rename the file Kermitt
        "https://i.imgur.com/n5lNz3z.jpg", // Watch the green ticks pleasure
        "https://i.imgur.com/tup8Ocu.jpg", // Sent you the app Anakin
        "https://i.imgur.com/yjpOvlM.jpg", // Scroll of truth
        "https://i.imgur.com/akNhnrh.jpg", // Thinking about other women
        "https://i.imgur.com/eqpDlh5.jpg", // Imma head out SpongeBob
        "https://i.imgur.com/Fgo7nnZ.jpg", // Two buttons ArgoCD Helm 
        "https://i.imgur.com/pCjM1d6.jpg", // The bug in my pipeline Momoa Cavill 
        "https://i.imgur.com/kGQUUTw.jpg", // GitOps goosebumps
        "https://i.imgur.com/o4LuRu7.jpg", // Automation feelings of power
        "https://i.imgur.com/CnDPSpV.png", // Automate all the things
        "https://i.imgur.com/E0s8TW6.png", // We are not the same
        "https://i.imgur.com/xSmJv0k.png" // Automation everywhere
    ];

ingress:
  annotations: {    
    kubernetes.io/ingress.class: alb,
    alb.ingress.kubernetes.io/scheme: internet-facing,
    alb.ingress.kubernetes.io/target-type: ip,
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP,
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port,
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15',
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5',
    alb.ingress.kubernetes.io/success-codes: '200',
    alb.ingress.kubernetes.io/healthy-threshold-count: '2',
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  }
