name: 02-Build & deploy my-app-backend image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'my-app/backend/**'

env:
  APP_NAME: AATT_APP_NAME # This value was modified by the initial-setup python script
  SERVICE: backend

jobs:
  build-and-push:
    name: Build & push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}-${{ env.SERVICE }}
          tag: ${{ github.run_number }}
          registry: docker.io
          directory: my-app/${{ env.SERVICE }}
          dockerfile: my-app/${{ env.SERVICE }}/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


  deploy-dev:
    name: Update image tag for DEV environment
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # We update the local repo with a pull just in case there have been any recent modifications
      - name: Update repo
        run: git pull

      - name: Update tag in values-dev.yaml
        run: |
          sed 's/tag:.*/tag: ${{github.run_number}}/g' helm/my-app/${{ env.SERVICE }}/environments/values-dev.yaml > helm/my-app/${{ env.SERVICE }}/environments/values-dev.temp
          mv helm/my-app/${{ env.SERVICE }}/environments/values-dev.temp helm/my-app/${{ env.SERVICE }}/environments/values-dev.yaml

      - name: Commit changes to GitHub
        run: |
          git config --global user.email "GitHubActions@Build&Deploy${{ env.SERVICE }}Workflow.com"
          git config --global user.name "GitHub Actions - Build & Deploy ${{ env.SERVICE }} Workflow"
          git add helm/my-app/${{ env.SERVICE }}/environments/values-dev.yaml 
          git commit -m "${{ env.SERVICE }} image tag updated to ${{github.run_number}} by GitHub Actions"
          git push


  deploy-stage:
    name: Update image tag for STAGE environment
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # We update the local repo with a pull just in case there have been any recent modifications
      - name: Update repo
        run: git pull

      - name: Update tag in values-stage.yaml
        run: |
          sed 's/tag:.*/tag: ${{github.run_number}}/g' helm/my-app/${{ env.SERVICE }}/environments/values-stage.yaml > helm/my-app/${{ env.SERVICE }}/environments/values-stage.temp
          mv helm/my-app/${{ env.SERVICE }}/environments/values-stage.temp helm/my-app/${{ env.SERVICE }}/environments/values-stage.yaml

      - name: Commit changes to GitHub
        run: |
          git config --global user.email "GitHubActions@Build&Deploy${{ env.SERVICE }}Workflow.com"
          git config --global user.name "GitHub Actions - Build & Deploy ${{ env.SERVICE }} Workflow"
          git add helm/my-app/${{ env.SERVICE }}/environments/values-stage.yaml 
          git commit -m "${{ env.SERVICE }} image tag updated to ${{github.run_number}} by GitHub Actions"
          git push


  deploy-prod:
    name: Update image tag for PROD environment
    needs: deploy-stage

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # We update the local repo with a pull just in case there have been any recent modifications
      - name: Update repo
        run: git pull

      - name: Update tag in values-prod.yaml
        run: |
          sed 's/tag:.*/tag: ${{github.run_number}}/g' helm/my-app/${{ env.SERVICE }}/environments/values-prod.yaml > helm/my-app/${{ env.SERVICE }}/environments/values-prod.temp
          mv helm/my-app/${{ env.SERVICE }}/environments/values-prod.temp helm/my-app/${{ env.SERVICE }}/environments/values-prod.yaml

      - name: Commit changes to GitHub
        run: |
          git config --global user.email "GitHubActions@Build&Deploy${{ env.SERVICE }}Workflow.com"
          git config --global user.name "GitHub Actions - Build & Deploy ${{ env.SERVICE }} Workflow"
          git add helm/my-app/${{ env.SERVICE }}/environments/values-prod.yaml 
          git commit -m "${{ env.SERVICE }} image tag updated to ${{github.run_number}} by GitHub Actions"
          git push
          
